name: Terraform Apply

on:
  workflow_call:
    inputs:
      regions:
        description: "A JSON Array containing a list of AWS regions to publish to"
        required: true
        type: string
      ecr_repository:
        description: "The ECR repository to publish to"
        required: true
        type: string
      ecr_push:
        description: "Whether or not to push the image."
        required: false
        default: true
        type: boolean
      pull:
        description: "Always attempt to pull all referenced images (default false)"
        required: false
        type: boolean
        default: false
      no_cache:
        description: "Do not use cache when building the image (default false)"
        required: false
        type: boolean
        default: false
      profile:
        description: "The AWS profile to use"
        required: true
        type: string
      docker_file_path:
        description: "The path to the Dockerfile"
        required: false
        type: string
        default: ./Dockerfile
      docker_context_path:
        description: "The path to the docker context"
        required: false
        type: string
        default: .
      docker_target:
        description: "The target to build"
        required: false
        type: string
      login_to_ghcr:
        description: "Login to GHCR"
        required: false
        type: boolean
        default: true
      platforms: 
        description: "Platforms to publish to."
        required: false
        type: string
        default: |
          linux/amd64
      prefix:
        description: "Prefix for docker image tags"
        required: false
        type: string
        default: ""
    secrets:
      AWS_ACCESS_KEY_ID:
        description: "The AWS Access Key ID used during publish and deploy."
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "The AWS Secret Access Key used during publish and deploy."
        required: true
      GITHUB_PAT:
        description: "A GitHub access token that has repo and read:packages scopes"
        required: false
      BUILD_ARGS:
        description: "Docker image build arguments"
        required: false
    outputs:
      tag:
        description: "The image tag"
        value: ${{ jobs.build-and-publish.outputs.tag }}

jobs:

  build-and-publish:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: ${{ fromJson(inputs.regions) }}
        profile: [ "${{ inputs.profile }}" ]
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "${{ matrix.region }}"
          mask-aws-account-id: 'no'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}"
          tags: |
            type=sha,enable=true,prefix=${{ inputs.prefix }},format=short

        # Publish expects the repo to already exist,
        # but in the initial bootstrap, it won't yet exist,
        # so exit gracefully
      - name: Check if repo exists
        id: check-repo
        run: |
          existing_repo=$(aws ecr describe-repositories --query "repositories[?repositoryName=='${{ inputs.ecr_repository }}'].repositoryName" --output text)
          if [ -n "${existing_repo}" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

        # This step is useful if the workflow is re-run,
        # and the repository has IMMUTABILITY enabled
      - name: Check if tag has already been published
        id: check-tag
        if: steps.check-repo.outputs.exists == 'true'
        run: |
          gitsha=$(git rev-parse --short HEAD)
          existing_tag=$(aws ecr list-images --repository-name "${{ inputs.ecr_repository }}" --query "imageIds[?imageTag=='$gitsha'].imageTag" --output text)
          if [ -n "${existing_tag}" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Login to ghcr.io
        if: ${{ inputs.login_to_ghcr }} && steps.check-tag.outputs.exists == 'false' && steps.check-repo.outputs.exists == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: steps.check-tag.outputs.exists == 'false' && steps.check-repo.outputs.exists == 'true'

      - name: Cache Docker layers
        uses: actions/cache@v2
        if: steps.check-tag.outputs.exists == 'false' && steps.check-repo.outputs.exists == 'true'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push to ECR
        uses: docker/build-push-action@v2
        if: steps.check-tag.outputs.exists == 'false' && steps.check-repo.outputs.exists == 'true'
        with:
          # All layers should be cached to optimize for multi-environment deploys
          # Can't cache locally. Blocked by https://github.com/docker/build-push-action/issues/252
          #cache-from: type=local,src=/tmp/.buildx-cache
          #cache-to: type=local,dest=/tmp/.buildx-cache
          cache-from: type=gha,src=/tmp/.buildx-cache
          cache-to: type=gha,dest=/tmp/.buildx-cache-new
          context: "${{ inputs.docker_context_path }}"
          file: "${{ inputs.docker_file_path }}"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.ecr_push }}
          pull: ${{ inputs.pull }}
          no-cache: ${{ inputs.no_cache }}
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ inputs.docker_target }}
          build-args: ${{ secrets.BUILD_ARGS }}
